### ISSUE TITLE
New rubygems release?

### ISSUE THREAD

**Issue by mwojo** [kreeti/kt-paperclip#113]
Hi all,

Thanks for carrying on development of this gem. Would it be possible to get a new version released to rubygems incorporating the recent changes? Specifically it'd be really helpful to have [Adjust version check to restore compatibility with non-rails projects](https://github.com/kreeti/kt-paperclip/commit/46357326d93700f34474bbf6ab1b37fc3f07aa8c) available in a release version.
I'm aware we can set the gem's source to this commit with bundler, but this is cumbersome for gems that expose their dependency to kt-paperclip through a gemspec, where specifying a source isn't possible and must be done on all dependent applications.

If this is already planned or there's some other criteria pending for a release please feel free to close this. Thanks again.

**Comment by ssinghi** [comment]
Done.
