### ISSUE TITLE
Mongoid issue with size file validation in version 7.2.0 using mongoid-paperclip gem

### ISSUE THREAD

**Issue by michel-victor** [kreeti/kt-paperclip#120]
Hello. This change on [attachment_size_validator.rb](https://github.com/kreeti/kt-paperclip/commit/46357326d93700f34474bbf6ab1b37fc3f07aa8c#diff-b0a75ee7c32c4bc9b4da980e10e8580d035508aeb578bafae1c1c9f55495adcf) breaks size validation when using the [mongoid-paperclip](https://github.com/mrrooijen/mongoid-paperclip) gem.

**Comment by ssinghi** [comment]
@michel-victor can you please provide more details on which Rails version and the error message/stacktrace. Thanks!

**Comment by michel-victor** [comment]
Hi @ssinghi,
Here are the details. Thanks!!!

---

Ruby 3.2.2
Rails 6.1.7.4
mongoid 7.5.3
mongoid-paperclip 0.1.0
kt-paperclip 7.2.0

```
  include Mongoid::Document
  include Mongoid::Paperclip

  has_mongoid_attached_file :csv

  validates_attachment :csv,
    presence: true,
    size: { less_than: 5.megabytes },
    content_type: { content_type: 'text/csv' }
```

`"NameError uninitialized constant Paperclip::Validators::AttachmentSizeValidator::ActiveRecord"`

**Comment by ssinghi** [comment]
@sbhawsingka i think perhaps the comparison should be on ActiveModel and not ActiveRecord. Can you please verify?

@michel-victor are you guys not using active_record gem in your application?

thanks!

**Comment by ssinghi** [comment]
@michel-victor can you please review https://github.com/kreeti/kt-paperclip/pull/122 ?

**Comment by michel-victor** [comment]
That's right, we use mongoid instead of active_record.
#122 Reviewed and approved.

Thank you so much!!! 🎉
