### ISSUE TITLE
application/vnd.ms-excel uploaded file with content type validation of text/csv doesn't work

### ISSUE THREAD

**Issue by mikeLspohn** [kreeti/kt-paperclip#33]
This is directly related to this issue on the original paperclip repo. https://github.com/thoughtbot/paperclip/issues/1924

I wasn't sure if issues like this should be addressed in this repo, but I was really hoping I could find some workaround than the one suggested there in turning off spoof checking for the files. My understanding is that the `file -b --mime` check on windows saved excel files produce the `application/vnd.ms-excel` mime-type. With the content-type `text/csv` specified in a model using paperclip this fails with `has contents that are not what they are reported to be`.

If issues like this aren't being addressed in this fork I understand, but figured it was worth a shot to ask about it. I would've used the issue template provided but honestly I'm not 100% familiar with the problem or how it happens. I don't have a windows machine or excel, but from what I've gathered from clients running into this issue, and then the linked GitHub issue I tried to give a description that hopefully helps. If it's too ambiguous no worries.

**Comment by pierre-alain-b** [comment]
Hi there, it seems to me that `application/vnd.ms-excel` is really what should be returned for MS Excel files. If the file is not a text/csv, it is normal that it fails. Is there no way for you to accept `application/vnd.ms-excel` in your application?
