### ISSUE TITLE
Fix warning : URI.escape is obsolete

### ISSUE THREAD

**Issue by zedalaye** [kreeti/kt-paperclip#35]
**Describe the bug**
When I use kt-paperclip on a Rails 6.0.3 application powered by Ruby 2.7.1 my logs are filled with this warning :

`/home/pierre/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kt-paperclip-6.3.0/lib/paperclip/url_generator.rb:68: warning: URI.escape is **obsolete**`

**To Reproduce**
Run a rails application with kt-paperclip on Ruby 2.7+

**Expected behavior**
No warnings are logged

**Additional context**
The `URI.escape` [documentation](https://ruby-doc.org/stdlib-2.7.1/libdoc/uri/rdoc/URI/Escape.html#method-i-escape-label-Description) has this statement:

```
    # This method is obsolete and should not be used. Instead, use
    # CGI.escape, URI.encode_www_form or URI.encode_www_form_component
    # depending on your specific use case.
``` 

Several Ruby projects have fixed this error, example: https://github.com/contentful/contentful.rb/pull/221/commits/82dd6df17caed705e67f2737282c97764c25d2b3#diff-606706a8b47f20495c7c206d12212665

**Comment by filipecabaco** [comment]
Any update on this issue?
