### ISSUE TITLE
"Paperclip::Errors::NotIdentifiedByImageMagickError" on Debian Buster, fixed by altering the config of imageMagic

### ISSUE THREAD

**Issue by pierre-alain-b** [kreeti/kt-paperclip#37]
**Describe the bug**
On an up-to-date Debian Buster machine, when trying to insert a PDF file with Paperclip, the error: `Paperclip::Errors::NotIdentifiedByImageMagickError`
is returned.

**To Reproduce**
1. Load a PDF file in a file-input field
2. Save
3. Look with horror at the error

**Expected behavior**
No error of course!

**Screenshots**
N/A

**Additional context**
The issue is likely linked to ImageMagick as here is the return of the convert command on a PDF file:
```
**convert 20F0001.pdf test.png**
convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408.
convert-im6.q16: no images defined `test.png' @ error/convert.c/ConvertImageCommand/3258.
zsh: exit 1     convert 20F0001.pdf test.png
```

**Comment by pierre-alain-b** [comment]
As a reference, a similar bug was declared here: https://github.com/thoughtbot/paperclip/issues/2538 back in 2018

**Comment by pierre-alain-b** [comment]
As this seems related to ImageMagick policy rules, this issue can be fixed by changing the policy: to fix it, I had to comment this line in /etc/ImageMagick-6/policy.xml :
`<policy domain="coder" rights="none" pattern="PDF" />`
(therefore the line became `<!-- <policy domain="coder" rights="none" pattern="PDF" /> -->`)

**Comment by zainzafar** [comment]
We got around uploading PDFs by skipping post processing.

```ruby
before_post_process :skip_for_pdf

def skip_for_pdf
  !%w(application/pdf).include?(asset_content_type)
end
```

**Comment by pierre-alain-b** [comment]
@zainzafar good to know if tweaking the policy of ImageMagick is not an option!
