### ISSUE TITLE
Bump version to include fix for Ruby 2.7

### ISSUE THREAD

**Issue by anhkind** [kreeti/kt-paperclip#42]
We already had the fix for deprecation warning for Ruby 2.7 here https://github.com/kreeti/kt-paperclip/commit/f0367733ddf37141ae00517c6697cc3dd233dab9. Should we bump the version to 6.3.1 or 6.4.0 and release the gem if possible? Thank you.

**Comment by ssinghi** [comment]
@anhkind Release new version 6.4.0 of the gem.
