### ISSUE TITLE
6.4.0 - Fix NoMethodError (private method `open' called for Paperclip::HttpUrlProxyAdapter)

### ISSUE THREAD

**Issue by v-kumar** [kreeti/kt-paperclip#44]
**Describe the bug**
When using ruby-2.7.x with kt-paperclip, get the deprecation warning:
```
kt-paperclip-6.4.0/lib/paperclip/io_adapters/uri_adapter.rb:56: 
warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
```

#35 fixed one part of the ruby-2.7 URI deprecation. This fix is needed for other parts.

However, 6.4 also broke the gem in rub 2.6

```
private method `open' called for Paperclip::HttpUrlProxyAdapter: :Paperclip::HttpUrlProxyAdapter
kt-paperclip-6.4.0/lib/paperclip/io_adapters/uri_adapter.rb:56:in `download_content'
```

**To Reproduce**
Run the gem in ruby-2.7. it will produce 
```
warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
```

Run 6.4.0 in ruby 2.6, it will error
```
NoMethodError (private method `open' called for Paperclip::HttpUrlProxyAdapter: :Paperclip::HttpUrlProxyAdapter)
kt-paperclip-6.4.0/lib/paperclip/io_adapters/uri_adapter.rb:56:in `download_content'
```

**Expected behavior**
No warnings are logged.

**Additional context**
See [ruby-lang issue:15893](https://bugs.ruby-lang.org/issues/15893).

[Rubocop also has a check](https://github.com/rubocop-hq/rubocop/issues/6216).

Note that the fix, to change from `self.open` to `URI.open` is compatible with ruby-2.5 and ruby-2.6.

If you still want to support ruby 2.4, the fix needs to be sensitive to ruby version.

i.,e

```
    if RUBY_VERSION < '2.5'
      def download_content
        options = { read_timeout: Paperclip.options[:read_timeout] }.compact

        open(@target, options)
      end
    else
      def download_content
        options = { read_timeout: Paperclip.options[:read_timeout] }.compact

        URI.open(@target, options)
      end
    end
```

I prefer changing the method itself based on ruby version rather than the open call as it makes it a gem load-time decision vs runtime.

**Comment by v-kumar** [comment]
@kreetitech @ssinghi Any update on this?

**Comment by ssinghi** [comment]
@v-kumar can you please create a PR to fix this? Thanks!

**Comment by v-kumar** [comment]
@ssinghi Here it is: https://github.com/kreeti/kt-paperclip/pull/45

**Comment by ssinghi** [comment]
Thanks once again @v-kumar
