### ISSUE TITLE
wrong number of arguments (given 3, expected 1..2) with validations on Rails 6.1

### ISSUE THREAD

**Issue by rmehner** [kreeti/kt-paperclip#46]
**Describe the bug**

When using kt-paperclip on Rails 6.1, when using validations that will trigger errors, Rails will throw a `wrong number of arguments (given 3, expected 1..2)` error.

See https://github.com/rails/rails/issues/41270 for details on that.

**To Reproduce**

```rb
class User < ApplicationRecord
  has_attached_file :avatar
  validates_attachment_presence :avatar, if: :confirmed?
end
```

This will trigger the error, if avatar is missing

**Expected behavior**

Should not trigger the error.

**Additional context**

Changing https://github.com/kreeti/kt-paperclip/blob/master/lib/paperclip/validators/attachment_presence_validator.rb#L7 to:

```rb
record.errors.add(attribute, :blank, **options) if record.send("#{attribute}_file_name").blank?
```

Fixes it for the presence validator. Not sure how compatible that would be to older versions though.

**Comment by ssinghi** [comment]
@rmehner If you can please create a PR for this, we can then take it forward. thanks!

**Comment by rmehner** [comment]
@ssinghi was planning to, but `bundle install` is stuck on `Resolving dependencies` for over 1h now on this project, so I can't run the tests. I might just do the changes and let the CI deal with it :)

**Comment by v-kumar** [comment]
@rmehner it is because of all the ruby versions and the needed gems. Takes a long time without proper RVM setup for all required ruby versions. I would recommend creating a PR and let Travis deal with it. Or, my PR just got merged and I can do this for you.

**Comment by rmehner** [comment]
It's stuck at the `bundle install` step, I've stopped it after 2 hours. I'll use CI for that then and will provide a PR soon-ish.

**Comment by brendon** [comment]
Hi @ssinghi, would you be able to release a gem with this fix in it?  :)

**Comment by ssinghi** [comment]
New gem version v7.0.0 released as well .

**Comment by brendon** [comment]
Thanks @ssinghi. Much appreciated :D

**Comment by rmehner** [comment]
Can confirm this works as expected. Thanks for your work @ssinghi, didn't came around to do it for myself.
