### ISSUE TITLE
Validation warnings

### ISSUE THREAD

**Issue by adrianmann** [kreeti/kt-paperclip#47]
**Describe the bug**
Warnings associated with attachment validators that I have seen during testing:
/.rvm/gems/ruby-2.7.1/gems/kt-paperclip-6.4.1/lib/paperclip/validators/attachment_presence_validator.rb:7: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

.rvm/gems/ruby-2.7.1/gems/kt-paperclip-6.4.1/lib/paperclip/validators/attachment_content_type_validator.rb:50: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

.rvm/gems/ruby-2.7.1/gems/activemodel-6.1.1/lib/active_model/errors.rb:404: warning: The called method `add' is defined here

**To Reproduce**
Using `validates_attachment` and `do_not_validate_attachment_file_type` validators.

**Expected behavior**
No warnings.

I am using Rails 6.1 and kt-paperclip 6.4.1.

**Comment by ssinghi** [comment]
This is a known issue #46 , if you can create a PR we can review and accept it. Thanks!

**Comment by adrianmann** [comment]
Closing as is in fact a [duplicate](https://github.com/kreeti/kt-paperclip/issues/46) as said above.
