### ISSUE TITLE
Plans for mimemagic problem?

### ISSUE THREAD

**Issue by jonatasrancan** [kreeti/kt-paperclip#53]
Hi guys, I just found about this fork, and since paperclip is deprecated, I don't think they will care about the problem related to mimemagic gem. So I thought here is the right place for this issue.

Did you guys already thought on how to solve this? Maybe try to reproduce what Rails is doing: https://github.com/rails/marcel/pull/26/files

For those who doesn't know what is going on: https://github.com/rails/rails/issues/41750

**Comment by jonatasrancan** [comment]
Sorry found this PR https://github.com/kreeti/kt-paperclip/pull/52/files just after I open the issue.

**Comment by ghiculescu** [comment]
FYI: https://github.com/kreeti/kt-paperclip/pull/54

If you're interested in testing it, see https://github.com/kreeti/kt-paperclip/pull/54#issuecomment-809529687
