### ISSUE TITLE
Problem with your .github/FUNDING.yml

### ISSUE THREAD

**Issue by frenkel** [kreeti/kt-paperclip#57]
When I click the sponsor button I get an error from Github that informs me there are issues with the file `.github/FUNDING.yml`. You might want to fix that for possible sponsors.

**Comment by edward-ellis** [comment]
@ssinghi, I think the second name in the FUNDING.yml is no longer valid.

**Comment by ssinghi** [comment]
Fixed. thanks!

**Comment by ssinghi** [comment]
Actually, we are from India, and Github hasn't extended their sponsorship program over here yet. So, it won't work.
Anyway, thank you for thinking of sponsoring this project.
