### ISSUE TITLE
Rails 6.1 tests fail

### ISSUE THREAD

**Issue by reedstonefood** [kreeti/kt-paperclip#60]
**Describe the bug**

The Rails 6.1 tests fail

**To Reproduce**

Look at the TravisCI results for 6.1, for example [here](https://travis-ci.com/github/kreeti/kt-paperclip/jobs/508937905).

**Expected behavior**

The tests should pass.

**Additional context**

I have created a [PR#59](https://github.com/kreeti/kt-paperclip/pull/59
) to fix the deprecation warnings that show up in that Travis run. Together with fixing these tests, it will make `kt-paperclip` ready to run on the newest versions of Rails (6.1 and the in-development 7.0) & Ruby (3.0).

**Comment by jlledom** [comment]
How safe would you say is it to upgrade to kt-paperclip 7.0.0 and rails 6.1 with those tests failing? is there any chance of data loss or any other serious issue?

**Comment by robmathews** [comment]
Well, it doesn't work, for example I get:

```
ActionView::Template::Error:
  undefined method `escape' for URI:Module
./vendor/bundle/ruby/3.0.0/gems/paperclip-6.1.0/lib/paperclip/url_generator.rb:68:in `escape_url'
```
which is because they've deprecated escape (you should use CGI.escape instead)

**Comment by ccarlson-oliver** [comment]
Alternatively, use `URI::Parser.new.escape()`, which implements an RFC 2396-compliant parser.

**Comment by ssinghi** [comment]
The fix has been merged, so closing the PR.
