### ISSUE TITLE
Fix `URI.escape is obsolete` warnings on Paperclip 4.x and 5.x

### ISSUE THREAD

**Issue by spaghetticode** [kreeti/kt-paperclip#68]
**The problem**

People that are not yet on Paperclip 6.x but on Ruby 2.7 have currently no alternative to upgrading to the latest major version in order to avoid seeing those deprecations, as KT Paperclip versions for 4.x and 5.x don't exist (yet?), so obviously they cannot incorporate the fix (which I think is included in https://github.com/kreeti/kt-paperclip/pull/38).

**Proposed solution**

I was wondering if it would be possible to release patch versions that include the fix for older major versions of Paperclip. I offer my help, if this makes sense to you.

**Additional context** 

As maintainers of [Solidus](https://github.com/solidusio/solidus), we have a [non-current major version](https://github.com/solidusio/solidus/tree/v2.11) still supported of the framework that is still using the original Paperclip, so all installations using this version running on ruby 2.7.x are emitting the above-mentioned deprecation. Paperclip requirement on this version is `>= 4.2`, so we should not change dependencies to new major versions (i.e. to KT Paperclip 6.3) as this would automatically break semantic versioning. This is the [PR](https://github.com/solidusio/solidus/pull/4174) that started the discussion on Solidus.

**Comment by spaghetticode** [comment]
@ssinghi is this something I can work on and my contribution would be welcome?

**Comment by ssinghi** [comment]
Hi @spaghetticode sure, please create PRs for those branches, if they look good, I can merge, and create new release versions.

**Comment by spaghetticode** [comment]
@ssinghi @sbhawsingka I was able to backport the fix to Paperclip 4.x (started from tag [v4.3.7](https://github.com/kreeti/kt-paperclip/tree/v4.3.7)), but given there's no 4.x branch on your github repository, I am not able to open a pull request (PRs can be opened only to an existing target branch). Same will happen with 5.x.

Still, you can see my changes here: https://github.com/kreeti/kt-paperclip/compare/v4.3.7...spaghetticode:kt-paperclip-4-x 
Specs are all green locally, but of course, given I can't open a PR I can't verify the CI on Travis.

Not sure how it's best to proceed, but I suppose that, if you create a v4.x branch, then I can submit my PR. Please let me know if there's any other path you want to follow, thank you!

**Comment by spaghetticode** [comment]
@ssinghi @sbhawsingka I backported the fix also to Paperclip 5.x, but again since there's not a branch on this fork to compare to, it's not possible to open a PR for that version. I hope we can overcome this problem. 

My changes are can be seen here: https://github.com/kreeti/kt-paperclip/compare/v5.3.0...spaghetticode:kt-paperclip-5-x?expand=1 and are very similar to the 4.x ones from my comment above.

I want to point out that the Rspec test suite is green, while Cucumber features are not working. I think this is expected, i.e. Cucumber was already failing with the original v5.3 release, given the vast amount of issues I found (some step definitions are not compatible with a Rails 5.x application). I don't think fixing these issues on 5.x is worth the effort, since it will require writing conditional code depending on what version of Rails is bundled during the tests (the Cucumber suite, as it stands now on both my branches, is green on rails < 5) and, after all, this is still unmaintained code.

**Comment by spaghetticode** [comment]
@ssinghi @sbhawsingka are you still interested in having these 2 releases done?

**Comment by ssinghi** [comment]
Hi @spaghetticode sorry for the delay, I have created the branches v4.x and v5.x.

https://github.com/kreeti/kt-paperclip/branches

Thank you for all your work!

**Comment by jarednorman** [comment]
Thanks so much @ssinghi! Looking forward to being able to get rid of more than 3000 warnings generated by one of our test suites thanks to this. 🙏🏻

**Comment by spaghetticode** [comment]
@ssinghi thank you very much for creating the branches, this helps us a lot and I really appreciate it ❤️ 

If possible, can you release official versions from these branches? That would be the icing on the cake 🎂 thanks!

**Comment by spaghetticode** [comment]
@ssinghi sorry I just realized these branches don't include yet my changes... and that makes totally sense 😅 
I've just opened a couple of PRs, I see there are some Hound complaints about code style, they're basically the same as the original PR on master and they were not corrected there... but let me know if you prefer me to remove them.

**Comment by ssinghi** [comment]
@spaghetticode released new gems with your changes v4.4.0 and v5.4.0. Thanks for all your work on fixing this.

Closing this issue.

**Comment by spaghetticode** [comment]
@ssinghi thank you very much, this is much appreciated ❤️ 🎉
