### ISSUE TITLE
Breaks After Rails 6 Upgrade 

### ISSUE THREAD

**Issue by jasonlogsdon** [kreeti/kt-paperclip#70]
In Rails 6, with Ruby 3.0.2, all calls return:
NoMethodError - undefined method `escape' for URI:Module:
I believe I'm using the latest version of kt-paperclip:
gem "kt-paperclip", git: "git://github.com/kreeti/kt-paperclip.git"
Thanks

**Comment by SeanLF** [comment]
@jasonlogsdon I think your issue comes from upgrading to Ruby 3. See #68

**Comment by jasonlogsdon** [comment]
Ah. Are there any plans to support ruby 3 in the future? Thanks!

**Comment by ssinghi** [comment]
@jasonlogsdon can you please upgrade to latest release and see if it fixes your issue.

**Comment by ssinghi** [comment]
@jasonlogsdon any updates?

**Comment by jasonlogsdon** [comment]
I'll check it out whenever I upgrade the project to ruby 3. Because of this and another gem I downgraded ruby so things would work. No current plans to upgrade in the near future but I'm glad I'll still be able to use this gem when I do. Thanks!
