### ISSUE TITLE
Rails 7 compatibility: missing CHECKS constant in AttachmentSizeValidator

### ISSUE THREAD

**Issue by SeanLF** [kreeti/kt-paperclip#71]
The `CHECKS` constant (as seen below) no longer exists in Rails 7. It seems to have been replaced by `COMPARE_CHECKS`
(there's also `NUMBER_CHECKS` & `RANGE_CHECKS`, though I don't think are relevant in this case)

https://github.com/kreeti/kt-paperclip/blob/0b7bb0b455aea0fa961a25c0c74e2bd33ae99ba9/lib/paperclip/validators/attachment_size_validator.rb#L39

https://github.com/rails/rails/blob/ceb4b94baaf17f3a9f4ea795c83ec6c67211f737/activemodel/lib/active_model/validations/numericality.rb#L11-L14

**Comment by yorzi** [comment]
I encountered the error when upgrading my app to Rails 7:
```
uninitialized constant Paperclip::Validators::AttachmentSizeValidator::CHECKS
```

Did anyone figure out this?

**Comment by yorzi** [comment]
I submitted a PR for this: https://github.com/kreeti/kt-paperclip/pull/73

**Comment by ssinghi** [comment]
Merged and Fixed.
