### ISSUE TITLE
paperclip-av-transcoder us

### ISSUE THREAD

**Issue by skanilabsinc** [kreeti/kt-paperclip#93]
I am using paperclip-av-transcoder for video processing and it has a dependency on paperclip. Although I have uninstalled the paperclip and installed the kt-paperclip. rails is still using paperclip gem to file.

Is there any solution available for paperclip-av-transcoder, so I can fully migrate to kt-paperclip

Thanks in advance.

**Comment by rocket-turtle** [comment]
The Question seems to be answered here.
https://github.com/ruby-av/paperclip-av-transcoder/issues/60

Solution was to remove the `paperclip-av-transcoder` gem so this issue can be closed :)

**Comment by skanilabsinc** [comment]
Yes, thanks
