### ISSUE TITLE
Ruby 2.7 Deprecation warning - fixed in 7.0 - can it be added to v 6.4.x?

### ISSUE THREAD

**Issue by wizardofelves** [kreeti/kt-paperclip#99]
Hi all, 

In February 2021 [adrianmann](https://github.com/adrianmann/kt-paperclip/commits?author=adrianmann) submitted this PR to address this issue: https://github.com/kreeti/kt-paperclip/issues/46

It was merged into version 7 of paperclip by [ssinghi](https://github.com/ssinghi)

Is it possible to have this PR also merged into V6 of paperclip and a new version of 6.4.x be pushed and released? 

The PR in question: https://github.com/kreeti/kt-paperclip/pull/48

**Comment by ssinghi** [comment]
@wizardofelves done

https://github.com/kreeti/kt-paperclip/releases/tag/v6.4.2

**Comment by wizardofelves** [comment]
Thanks!
